import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');
</style>

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Para meu amor!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
